services:
  db:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: "ny_taxi"
    ports:
      - "5431:5432"
    volumes:
      - ./ny_taxi_postgres_data:/var/lib/postgresql/data
    networks:
      - pgnetwork
  
  ui:
    image: dpage/pgadmin4
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: root@domain.com
      PGADMIN_DEFAULT_PASSWORD: root
    networks:
      - pgnetwork

networks:
    pgnetwork:
      external: true
